on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: sudo rm -f /var/lib/man-db/auto-update  # Workaround for https://github.com/actions/runner/issues/4030
    - run: sudo apt-get install --yes gperf
    - run: autoconf
    - run: ./configure
    - run: make
